# Generated by Django 3.1.2 on 2020-10-30 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('idBoleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='sysdate')),
                ('monto', models.IntegerField()),
            ],
            options={
                'db_table': 'boleta',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCat', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('puntos', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepa', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='sysdate')),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.cliente')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreModelo', models.CharField(max_length=50)),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.marca')),
            ],
            options={
                'db_table': 'modelo',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=40)),
                ('apePat', models.CharField(max_length=40)),
                ('apeMat', models.CharField(max_length=40)),
                ('fono', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProv', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProv', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('razonSocial', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idVendedor', models.AutoField(primary_key=True, serialize=False)),
                ('sueldoBase', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('bono', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('idDepa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.departamento')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.persona')),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('idFono', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFono', models.IntegerField()),
                ('compañia', models.CharField(max_length=20)),
                ('idPersona', models.IntegerField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.factura')),
            ],
            options={
                'db_table': 'telefono',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProd', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
                ('garantia', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fichaTecnica', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.marca')),
                ('idModelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.modelo')),
                ('idProv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.proveedor')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='modelo',
            name='idProv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.proveedor'),
        ),
        migrations.AddField(
            model_name='marca',
            name='idProv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.proveedor'),
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('idGasto', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='sysdate')),
                ('idProv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.proveedor')),
            ],
            options={
                'db_table': 'gastos',
            },
        ),
        migrations.CreateModel(
            name='Factura_null',
            fields=[
                ('idFacNull', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='sysdate')),
                ('descripcion', models.CharField(max_length=200)),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.factura')),
            ],
            options={
                'db_table': 'factura_null',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='idProv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.proveedor'),
        ),
        migrations.CreateModel(
            name='Deterioro',
            fields=[
                ('idDeterioro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(verbose_name='sysdate')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.producto')),
            ],
            options={
                'db_table': 'deterioro',
            },
        ),
        migrations.CreateModel(
            name='DetalleFac',
            fields=[
                ('idDetFac', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.producto')),
            ],
            options={
                'db_table': 'detalle_fac',
            },
        ),
        migrations.CreateModel(
            name='DetalleBol',
            fields=[
                ('idDetBol', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadProd', models.IntegerField()),
                ('idBoleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.boleta')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.producto')),
            ],
            options={
                'db_table': 'detalle_bol',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='idPersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.producto'),
        ),
        migrations.CreateModel(
            name='Boleta_null',
            fields=[
                ('idBolNull', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='sysdate')),
                ('descripcion', models.CharField(max_length=200)),
                ('idBoleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.boleta')),
            ],
            options={
                'db_table': 'boleta_null',
            },
        ),
        migrations.AddField(
            model_name='boleta',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='idVendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenedor.vendedor'),
        ),
    ]
