# Generated by Django 3.1 on 2020-09-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region3',
            fields=[
                ('idcom', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.DateTimeField(verbose_name='Nombre Region')),
            ],
            options={
                'db_table': 'aaaaa',
            },
        ),
    ]
